<a href="https://colab.research.google.com/github/TatyanaLanceva/Netology/blob/main/7_1_Linear_algebra_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
### YOUR CODE HERE
import numpy as np

# Создайте матрицу 3 на 3, заполненную числами от 1 до 9
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f'Телефонная матрица:\n {matrix}')
print()

matrix1 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])
print(f'Матрица с единицами по диагонали:\n {matrix1}')
print()

# Прибавьте к ней матрицу с единицами на диагонале
summatrix = matrix + matrix1
print(f'Сумма первых двух матриц:\n {summatrix}')
print()

# Определение вектора (как одномерного массива)
v = np.array([1, 2, 3])
v = v.reshape(-1, 1)
# Умножьте полученную матрицу на вектор (1, 2, 3)
v_multiply = summatrix @ v
print(f'Результат умножения суммы матриц на вектор:\n {v_multiply}')
print()

# Вычислить транспонированную матрицу AT от полученной в результате прибавления матрицы
AT = summatrix.T
print(f'Транспонированная матрица:\n {AT}')
print()

# Посчитайте обратную матрицу к полученной в результате прибавления матрице
# Проверка определителя
determinant = np.linalg.det(summatrix)

if determinant == 0:
    print("Матрица вырожденная. Обратная матрица не существует.")
else:
    inverse_matrix = np.linalg.inv(summatrix)
    print(f'Обратная матрица:\n {inverse_matrix}')


Телефонная матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица с единицами по диагонали:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

Сумма первых двух матриц:
 [[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]

Результат умножения суммы матриц на вектор:
 [[15]
 [34]
 [53]]

Транспонированная матрица:
 [[ 2  4  7]
 [ 2  6  8]
 [ 3  6 10]]

Обратная матрица:
 [[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
### YOUR CODE HERE
# Определение матрицы
m = np.array([[2, 2],
              [1, 3]])
print(f'Матрица:\n {m}')
print()

# Вычисление собственных значений и собственных векторов
eigenvalues, eigenvectors = np.linalg.eig(m)

# Вывод результатов
print(f'Собственные значения:\n {eigenvalues}')
print()

print(f'Собственные векторы (по столбцам):\n {eigenvectors}')

Матрица:
 [[2 2]
 [1 3]]

Собственные значения:
 [1. 4.]

Собственные векторы (по столбцам):
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
### YOUR CODE HERE

# Матрица 2x2 с определителем 1 и без нулевых элементов
matrix = np.array([
    [1, 1],
    [1, 2]
])

# Проверка определителя
det = np.linalg.det(matrix)

print("Матрица:")
print(matrix)
print(f"Определитель: {det}")

Матрица:
[[1 1]
 [1 2]]
Определитель: 1.0
